env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - prettier
parser: '@typescript-eslint/parser'
settings:
  react:
    version: 'detect'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'no-use-before-define': 'off',
    'react/no-unescaped-entities': 'off',
    '@typescript-eslint/no-use-before-define': ['error'],
  }
